CyberDucks/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls'))
]

accounts/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    # Home Dashboard
    path('', views.home, name='home'),

    # Account Creation/ Login
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('signup/', views.signup, name='signup'),

    # Tasks
    path('tasks/', views.tasks, name='tasks'),
    path('tasks/create/', views.createTask, name='task_creation'),
    path('tasks/update/<str:task_id>', views.updateTask, name='update_task'),
    path('tasks/delete/<str:task_id>', views.deleteTask, name='delete_task'),
    path('tasks/<str:task_id>/', views.task, name='task_view'),

    # Notes
    path('notes/create/<str:task_id>/', views.createNote, name='note_creation'),
    path('notes/delete/<str:note_id>', views.deleteNote, name='delete_note'),

    # Projects
    path('projects/', views.projects, name='projects'),
    path('projects/create/', views.createProject, name='project_creation'),
    path('projects/createtask/<str:project_id>/', views.createProjectTask, name='project_task_creation'),
    path('projects/update/<str:project_id>', views.updateProject, name='update_project'),
    path('projects/delete/<str:project_id>', views.deleteProject, name='delete_project'),
    path('projects/<str:project_id>/', views.project, name='project_view'),
]

accounts/models.py
import uuid

from django.db import models
from django.contrib.auth.models import User


class Project(models.Model):
    # id = models.AutoField(primary_key=True)
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    title = models.CharField(max_length=256, null=True)
    description = models.TextField(null=True, blank=True)
    STATUS_CHOICES = [
        ('NEW', 'New'),
        ('OPN', 'Open'),
        ('COM', 'Completed'),
        ('SUS', 'Suspended'),
    ]
    status = models.CharField(
        max_length=3,
        choices=STATUS_CHOICES,
        default=0,
    )
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    client_name = models.CharField(max_length=256, null=True, blank=True)
    client_email = models.EmailField(max_length=256, null=True, blank=True)
    repo = models.URLField(null=True, blank=True)
    assigned_to = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Task(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    title = models.CharField(max_length=256, null=True)
    description = models.TextField(null=True, blank=True)
    STATUS_CHOICES = [
        ('NEW', 'New'),
        ('OPN', 'Open'),
        ('COM', 'Completed'),
        ('SUS', 'Suspended'),
    ]
    status = models.CharField(
        max_length=3,
        choices=STATUS_CHOICES,
        default=0,
    )
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    PRIORITY_CHOICES = [
        ('LW', 'Low'),
        ('MD', 'Medium'),
        ('HI', 'High'),
        ('CR', 'Critical'),
    ]
    priority = models.CharField(
        max_length=2,
        choices=PRIORITY_CHOICES,
        default=0,
    )
    assigned_to = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.title


class Note(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    title = models.CharField(max_length=256, null=True)
    note = models.TextField(null=True, blank=True)
    task = models.ForeignKey(Task, on_delete=models.SET_NULL, null=True)
    creator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import *
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .queries import *


# Authentication
@login_required(login_url='login')
def home(request):
    today_tasks = getTasksToday(request)
    project_completion = projectCompletion(request)
    context = {
        'tasksToday': today_tasks,
        'project_completion': project_completion,
    }
    return render(request, 'accounts/index.html', context)


def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.info(request, 'Username OR password is incorrect')
    context = {}
    return render(request, 'accounts/login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('login')


def signup(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request,'Account Created Successfully')

            return redirect('login')

    context = {
        'form': form
    }
    return render(request, 'accounts/signup.html', context)


# Tasks
@login_required(login_url='login')
def tasks(request):
    tasks_list = Task.objects.filter(assigned_to__exact=request.user)
    new_tasks = tasks_list.filter(status__exact='NEW').count()
    open_tasks = tasks_list.filter(status__exact='OPN').count()
    completed_tasks = tasks_list.filter(status__exact='COM').count()
    suspended_tasks = tasks_list.filter(status__exact='SUS').count()

    context = {
        'tasks': tasks_list,
        'new': new_tasks,
        'open': open_tasks,
        'completed': completed_tasks,
        'suspended': suspended_tasks,
    }
    return render(request, 'accounts/tasks.html', context)


@login_required(login_url='login')
def task(request, task_id):
    form = NoteForm()
    task_obj = Task.objects.get(id__exact=task_id)
    notes = Note.objects.filter(task__exact=task_obj)
    context = {
        'task': task_obj,
        'notes': notes,
        'form': form,
    }
    if request.user == task_obj.assigned_to:
        return render(request, 'accounts/task.html', context)
    else:
        return render(request, 'accounts/error')


@login_required(login_url='login')
def createTask(request):
    form = TaskForm()
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            submit = form.save(commit=False)
            submit.assigned_to = request.user
            submit.save()
            return redirect('/tasks/')

    context ={
        'form': form,
    }
    return render(request, 'accounts/forms/task.html', context)


@login_required(login_url='login')
def updateTask(request, task_id):
    print("\n\n\nCalled updateTask\n\n")
    task_obj = Task.objects.get(id=task_id)
    notes = Note.objects.filter(task__exact=task_obj)
    form1 = TaskForm(instance=task_obj)
    context = {
        'form': form1,
        'id': task_id,
        'notes': notes,
        'task': task_obj,
    }
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task_obj)
        if form.is_valid():
            submit = form.save(commit=False)
            # Don't need to reassign the user
            # submit.assigned_to = request.user
            submit.save()
            return redirect('/tasks/' + task_id)
    return render(request, 'accounts/forms/task_update.html', context)


@login_required(login_url='login')
def deleteTask(request, task_id):
    task_obj = Task.objects.get(id=task_id)
    if request.method == "POST":
        task_obj.delete()
        return redirect('/tasks/')
    context ={
        'task': task_obj
    }
    return render(request, 'accounts/forms/task.html', context)


# Notes
@login_required(login_url='login')
def deleteNote(request, note_id):
    note_obj = Note.objects.get(id=note_id)
    task_id = str(note_obj.task.id)
    if request.method == "POST":
        note_obj.delete()
    return redirect('/tasks/' + task_id)


@login_required(login_url='login')
def createNote(request, task_id):

    form = NoteForm()
    task_obj = Task.objects.get(id__exact=task_id)
    notes = Note.objects.filter(task__exact=task_obj)

    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            submit = form.save(commit=False)
            submit.creator = request.user
            submit.task = task_obj
            submit.save()
            return redirect('/tasks/' + task_id)

    context = {
        'form': form,
        'notes': notes,
        'task': task_obj,
    }
    return render(request, 'accounts/task.html', context)


# Project
@login_required(login_url='login')
def projects(request):
    project_list = Project.objects.filter(assigned_to__exact=request.user)
    new_projects = project_list.filter(status__exact='NEW').count()
    open_projects = project_list.filter(status__exact='OPN').count()
    completed_projects = project_list.filter(status__exact='COM').count()
    suspended_projects = project_list.filter(status__exact='SUS').count()

    context = {
        'projects': project_list,
        'new': new_projects,
        'open': open_projects,
        'completed': completed_projects,
        'suspended': suspended_projects,
    }
    return render(request, 'accounts/projects.html', context)


@login_required(login_url='login')
def project(request, project_id):
    project_obj = Project.objects.get(id__exact=project_id)
    tasks_list = Task.objects.filter(project__id__exact=project_id)
    form = ProjectTaskForm()
    labels = ['New', 'Open', 'Completed', 'Suspended']
    data = [tasks_list.filter(status__exact='NEW').count(), tasks_list.filter(status__exact='OPN').count(),
            tasks_list.filter(status__exact='COM').count(), tasks_list.filter(status__exact='SUS').count()]

    context = {
        'tasks': tasks_list,
        'project': project_obj,
        'form': form,
        'labels': labels,
        'data': data,
    }
    if request.user == project_obj.assigned_to:
        return render(request, 'accounts/project.html', context)
    else:
        return render(request, 'accounts/error')


@login_required(login_url='login')
def createProject(request):
    form = ProjectCreateForm()
    if request.method == 'POST':
        form = ProjectCreateForm(request.POST)
        if form.is_valid():
            submit = form.save(commit=False)
            submit.assigned_to = request.user
            submit.save()
            return redirect('/projects/')

    context = {
        'form': form,
    }
    return render(request, 'accounts/forms/project.html', context)


@login_required(login_url='login')
def deleteProject(request, project_id):
    project_obj = Project.objects.get(id=project_id)
    if request.method == "POST":
        project_obj.delete()
        return redirect('/projects/')


@login_required(login_url='login')
def createProjectTask(request, project_id):
    form = ProjectTaskForm()
    if request.method == 'POST':
        form = ProjectTaskForm(request.POST)
        if form.is_valid():
            submit = form.save(commit=False)
            submit.project = Project.objects.get(id__exact=project_id)
            submit.assigned_to = request.user
            submit.save()
            return redirect('/projects/' + project_id)


@login_required(login_url='login')
def updateProject(request, project_id):
    project_obj = Project.objects.get(id=project_id)
    form = ProjectForm(instance=project_obj)
    task_list = Task.objects.filter(project__id__exact=project_id)
    labels = ['New', 'Open', 'Completed', 'Suspended']
    data = [task_list.filter(status__exact='NEW').count(), task_list.filter(status__exact='OPN').count(),
            task_list.filter(status__exact='COM').count(), task_list.filter(status__exact='SUS').count()]
    context ={
        'form': form,
        'id': project_id,
        'tasks': task_list,
        'project': project_obj,
        'labels': labels,
        'data': data,
    }
    if request.method == 'POST':
        form = ProjectForm(request.POST, instance=project_obj)
        if form.is_valid():
            submit = form.save(commit=False)
            submit.save()
            return redirect('/projects/' + project_id)
    return render(request, 'accounts/forms/project_update.html', context)

accounts/templates/accounts/project.html
{% extends 'accounts/templates/base.html' %}

{% block title %}
    Projects
{% endblock %}

{% block SectionTitle %}
    Projects
{% endblock %}

{% block addButton %}
    <div>
        <a href='{% url 'projects' %}'
           class="d-none d-sm-inline-block btn btn-sm btn-green shadow-sm font-weight-bold text-gray-100"><i
                class="fas fa-arrow-left fa-sm text-gray-100 ml-1"></i> Back</a>
        <a href='{% url 'update_project' project.id %}'
           class="d-none d-sm-inline-block btn btn-sm btn-warning shadow-sm font-weight-bold text-gray-100">Edit
            <i
                    class="fas fa-edit fa-sm text-gray-100 ml-1"></i></a>
        <a href='#' data-toggle="modal" data-target="#deleteModal"
           class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm font-weight-bold text-gray-100">Delete
            <i
                    class="fas fa-trash fa-sm text-gray-100 ml-1"></i></a>
    </div>
{% endblock %}

{% block content %}

    <!-- Content Row -->

    <div class="row">

        <!-- project -->
        <div class="col-xl-8 col-lg-7 mb-4" style="height: 65vh">
            <div class="card shadow mb-4" style="height: 100%;">
                <!-- Card Header - Dropdown -->
                <div
                        class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-green">{{ project.title }}</h6>
                    <div class="dropdown no-arrow">

                    </div>
                </div>
                <!-- Card Body -->
                <div class="card-body" style="overflow-y: scroll">
                    <form>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="inputEmail4">Title</label>
                                <input disabled type="text" class="form-control" id="inputEmail4"
                                       value="{{ project.title }}">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputState">Status</label>
                                <select disabled id="inputState" class="form-control">
                                    <option selected>{{ project.get_status_display }}</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="exampleFormControlTextarea1">Description</label>
                                <textarea disabled class="form-control" id="exampleFormControlTextarea1"
                                          rows="3">{{ project.description }}</textarea>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="inputState2">Start Date</label>
                                <input disabled type="datetime-local" class="form-control" id="inputState2"
                                       value="{{ project.start_date }}">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputState3">End Date</label>
                                <input disabled type="datetime-local" class="form-control" id="inputState3"
                                       value="{{ project.end_date }}">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="inputState2">Contact Name</label>
                                <input disabled type="text" class="form-control" id="inputState2"
                                       value="{{ project.client_name }}">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputState">Contact Email</label>
                                <input disabled type="text" class="form-control" id="inputState2"
                                       value="{{ project.client_email }}">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="repo">Repository</label>
                                <input disabled type="text" class="form-control" id="repo"
                                       value="{{ project.repo }}">
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>

        <!-- Notes -->
        <div class="col-xl-4 col-lg-5 mb-4" style="height: 65vh">
            <div class="card shadow mb-4" style="height: 100%">
                <!-- Card Header - Dropdown -->
                <div
                        class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-green">Project Distribution</h6>
                    <div class="dropdown no-arrow">
                    </div>
                </div>
                <!-- Card Body -->
                <div class="card-body" style="overflow-y: scroll">
                    <canvas id="pie-chart"
                            style="margin:auto; position: absolute;top: 0;bottom: 0;left: 0;right: 0;"></canvas>
                </div>

            </div>
        </div>


    </div>
    <div class="row">

        <!-- Tables -->
        <div class="col-xl-12 ">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div
                        class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-green">Task List</h6>
                    <div class="dropdown no-arrow">
                        <a href='#' data-toggle="modal" data-target="#TaskModal"
                           class="d-none d-sm-inline-block btn btn-sm btn-green shadow-sm font-weight-bold text-gray-100">Create
                            <i
                                    class="fas fa-plus fa-sm text-gray-100 ml-1"></i></a>
                    </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <table class="table-curved" id="dataTable" style="width: 100%" cellspacing="0">
                        <thead>
                        <tr class="table-row-header-custom">
                            <th>Title</th>
                            <th>Status</th>
                            <th>Priority</th>
                            <th>Project</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for i in tasks %}
                            <tr class="{{ i.get_status_display }} clickable-row" data-href='../../tasks/{{ i.id }}'>
                                <td>{{ i.title }}</td>
                                <td>{{ i.get_status_display }}</td>
                                <td>{{ i.get_priority_display }}</td>
                                <td>{{ i.project }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>



    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content" style="border-radius: 20px">
                <div class="modal-header bg-dark-secondary"
                     style="border-top-left-radius: 15px; border-top-right-radius: 15px;">
                    <h5 class="modal-title" id="deleteModalLabel">Are you sure you want to delete?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body bg-dark-theme">
                    Select "Delete" below to verify your decision.
                </div>
                <form action="{% url 'delete_project' project.id %}" method="POST">
                    {% csrf_token %}
                    <div class="modal-footer bg-dark-theme"
                         style="border-bottom-left-radius: 15px; border-bottom-right-radius: 15px;">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <input type="submit" class="btn btn-outline-danger" name="Delete">
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="modal fade" id="TaskModal" tabindex="-1" role="dialog" aria-labelledby="TaskModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content" style="border-radius: 20px">
                <div class="modal-header bg-dark-secondary"
                     style="border-top-left-radius: 15px; border-top-right-radius: 15px;">
                    <h5 class="modal-title" id="TaskModalLabel">Create Task</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{% url 'project_task_creation' project.id %}" method="POST">
                    {% csrf_token %}
                    <div class="modal-body bg-dark-theme">
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="inputEmail4">Title</label>
                                {{ form.title }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="exampleFormControlTextarea1">Description</label>
                                {{ form.description }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="inputState2">Start Date</label>
                                {{ form.start_date }}
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputState3">End Date</label>
                                {{ form.end_date }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="inputState2">Status</label>
                                {{ form.status }}
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputState3">Priority</label>
                                {{ form.priority }}
                            </div>
                        </div>


                    </div>
                    <div class="modal-footer bg-dark-theme"
                         style="border-bottom-left-radius: 15px; border-bottom-right-radius: 15px;">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <input type="submit" class="btn btn-outline-success" name="Delete">
                    </div>
                </form>

            </div>
        </div>
    </div>


{% endblock %}

{% block AdditionalScripts %}
    <script>

        var config = {
            type: 'doughnut',
            data: {
                datasets: [{
                    data: {{ data|safe }},
                    backgroundColor: [
                        '#36b9cc', '#f6c23e', '#1cc88a', '#e74a3b'
                    ],
                    label: 'Tasks'
                }],
                labels: {{ labels|safe }}
            },
            options: {
                responsive: true,
                legend: {
                    display: true,
                    position: 'left',
                    align: 'center'
                }
            }
        };

        window.onload = function () {
            var ctx = document.getElementById('pie-chart').getContext('2d');
            window.myPie = new Chart(ctx, config);
        };

    </script>
{% endblock %}

accounts/templates/accounts/projects.html
{% extends 'accounts/templates/base.html' %}

{% block title %}
    Projects
{% endblock %}

{% block SectionTitle %}
    Projects
{% endblock %}

{% block addButton %}
    <a href="{% url 'project_creation' %}"
       class="d-none d-sm-inline-block btn btn-sm btn-green shadow-sm font-weight-bold text-gray-100">Add Project
        <i
                class="fas fa-plus fa-sm text-gray-100 ml-1"></i></a>
{% endblock %}

{% block content %}
    <!-- Content Row -->
    <div class="row">

        <!-- New -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">
                                New Project
                            </div>
                            <div class="h5 mb-0 font-weight-bold ">{{ new }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                Open Project
                            </div>
                            <div class="h5 mb-0 font-weight-bold ">{{ open }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                Completed Project
                            </div>
                            <div class="h5 mb-0 font-weight-bold ">{{ completed }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Pending Requests Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-danger shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-danger text-uppercase mb-1">
                                Suspended Project
                            </div>
                            <div class="h5 mb-0 font-weight-bold ">{{ suspended }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Content Row -->

    <div class="row">

        <!-- Tables -->
        <div class="col-xl-12 ">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div
                        class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-green">Project List</h6>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <table class="table-curved" id="dataTable" style="width: 100%" cellspacing="0">
                        <thead>
                        <tr class="table-row-header-custom">
                            <th>Title</th>
                            <th>Status</th>
                            <th>Contact Name</th>
                            <th>Contact Email</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for i in projects %}
                            <tr class="{{ i.get_status_display }} clickable-row" data-href='{{ i.id }}'>
                                <td>{{ i.title }}</td>
                                <td>{{ i.get_status_display }}</td>
                                <td>{{ i.client_name }}</td>
                                <td>{{ i.client_email }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>

    <script>
        jQuery(document).ready(function ($) {
            $(".clickable-row").click(function () {
                window.location = $(this).data("href");
            });
        });
    </script>

{% endblock %}